### ISSUE TITLE
Disambiguating between different subclasses

### ISSUE THREAD

**Issue by iravid** [sigma/marshal.el#4]
Hi there @sigma, I've started using this great library in https://github.com/ensime/ensime-emacs/pull/673, and ran into a slight issue. Wondering if perhaps you could provide some advice.

Our use-case is mirroring a server-side protocol. We're using the `plist` driver. 

In some of the protocol messages, there are fields that are required to be subtypes of a given type. For example:
```scala
final case class RefactorReq(
  procId: Int,
  params: RefactorDesc,
  interactive: Boolean
)
```

Here, `params` can be one of several messages; we need to disambiguate between them by consing the name of the constructor to the plist; e.g.
```
(:ensime-api-rename-refactor-desc (:new-name "bar" :file "foo.scala" :start 1 :end 100))
```

I'd be happy to add this functionality to the package, but need some guidance on how to approach that. I was thinking that this disambiguation should only be activated if a slot's type is a class marked `:abstract t`.

Any thoughts?

**Comment by sigma** [comment]
Hey, thanks for that, it's a very interesting use case (and I'm happy you find this package generally useful).
I definitely haven't thought this through, but my knee-jerk reaction is to be slightly concerned about changing the shape of the representation with this "indirection".
I'm wondering if having the following could look more homogeneous?
- a slot type marked `:abstract t :class-slot -cls`
- `(:-cls ensime-api-rename-refactor-desc :new-name "bar" :file "foo.scala" :start 1 :end 100)`

(`-cls` could even be the default value for `class-slot`, for simplicity)

I guess that would allow to keep things consistent when we're directly unmarshalling this object with its concrete type, vs when we're unmarshalling its parent.
I don't know, maybe I'm over-thinking it :)
What do you think?

**Comment by iravid** [comment]
I think your approach definitely has the benefit of consistency. I'm trying to conform to a pre-existing protocol, so I don't have the luxury of changing it :-) I also wouldn't want to force our protocol on your package.

Perhaps a more scalable way of approaching this is one of two:
- Supporting optional disambiguation through a driver-provided callback (similar to how `marshal-preprocess/postprocess` are available now for overriding); we can then inherit from the plist driver and provide this callback
- Changing the package API to support drivers that determine the type of the class being marshalled/unmarshalled from the data - we can then implement a separate `plist-with-disambiguation` driver

**Comment by sigma** [comment]
oh sorry, what I had in mind was precisely to use `marshal-preprocess/postprocess` to convert betweeen your protocol objects and my "flattened" representation above. Do you think that'd work?
If not, I'm definitely open to another driver-level override

**Comment by iravid** [comment]
Could you sketch out how that looks? I toyed with that last night but stopped because the interface doesn't allow the result of `preprocess` to determine the type being unmarshalled

**Comment by iravid** [comment]
Oh, I understand now; you plan on changing the default representation to what you described, and then we can use pre/postprocess to convert to our representation.

That sounds great.

I would stick with only using the disambiguated representation if you're working on an abstract class, as concrete classes and primitives already are disambiguated.

**Comment by sigma** [comment]
yes, exactly.

And I agree, there's no need to overload objects with concrete classes with that kind of information.
Do you want to take a stab at that? Otherwise I can put it on my todo-list, but it might not get done right away.

**Comment by iravid** [comment]
I'd love to! I'm still digesting the code, so if you have an idea of the changes required to do this, that would be helpful. Otherwise I'll poke around and see what comes up :-)

**Comment by sigma** [comment]
So at a high-level I suspect most of the changes should be in 
- `marshal-internal` (https://github.com/sigma/marshal.el/blob/master/marshal.el#L326) : maybe adding an artificial "slot" at https://github.com/sigma/marshal.el/blob/master/marshal.el#L334 to contain the concrete class
- `unmarshal--obj` (https://github.com/sigma/marshal.el/blob/master/marshal.el#L368) : probably adding some more logic to replace the class at https://github.com/sigma/marshal.el/blob/master/marshal.el#L378 with something from `marshal-info`

Then again, it's entirely possible I'm missing out on a few details :)

**Comment by iravid** [comment]
Thanks. I'll take a stab at that sometime soon.

**Comment by sigma** [comment]
I think that should now "just work" in v0.8.0 now that the code tries harder to make the round-trip marshal/unmarshal the identity operation
