### ISSUE TITLE
magit-gh-pulls and "Driver has not been opened in read mode" in 0.8.0

### ISSUE THREAD

**Issue by aaronjensen** [sigma/marshal.el#7]
Hi, 

When creating a pull request with magit-gh-pulls after upgrading marshal.el to 0.8.0, I get this message:

```
Driver has not been opened in read mode
```

It still opens the pull request, but it doesn't close the message window or copy the pull url to the clipboard. Reverting to 0.7.0 works fine.

Thanks!

**Comment by sigma** [comment]
oops, sorry about that. It should be fixed in 0.8.1

Thanks for the report !

**Comment by aaronjensen** [comment]
Confirmed, thank you!
